Create new cfg for next Yocto release, rename LICENSE_FLAGS_WHITELIST->_ACCEPTED
This is required in future releases (kirkstone):

  $ bitbake $BITBAKE_TARGET
  ERROR: Variable LICENSE_FLAGS_WHITELIST has been renamed to
  	 LICENSE_FLAGS_ACCEPTED (file:
	 /.../builds/raspberrypi3-mesa-wpe-2.34/conf/presets/conf_v2.conf
         line: 28)

The rest of the contents of "conf_v3.conf" are the same as "v2".