bubblewrap,xdg-dbus-proxy: Update SRC_URI to change BPN instead of PN
Fixes
ERROR: QA Issue: bubblewrap: SRC_URI uses PN not BPN [src-uri-bad]

Signed-off-by: Khem Raj <raj.khem@gmail.com>